### ISSUE TITLE
Service 'microservice' failed to build

### ISSUE THREAD

**Issue by atammi** [strongloop/apiconnect-docker#49]
Using: Windows 10 Pro, Docker for Windows 18.06.1-ce-win73 (19507), docker-compose 1.22.0

I followed the installation instruction in README.md and when reaching Startup Options I selected 'Using DataPower Gateway' option. 

Then 'docker-compose up -d' runs smoothly for a while but then gives me this error when building microservice. Checking with google someone suggested that Block-scoped declarations error is Node version issue but that's all.

> docker-compose up -d
...
Building microservice
Step 1/12 : FROM node:4-slim
 ---> c953ec480e11
Step 2/12 : RUN mkdir -p /usr/src/app &&     apt update &&     apt install -y jq &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 3a6d63b3fb01
Step 3/12 : WORKDIR /usr/src/app
 ---> Using cache
 ---> 7c268974a66d
Step 4/12 : COPY package.json /usr/src/app/
 ---> 6865555e7f43
Step 5/12 : RUN npm install --silent -g npm &&     npm install --silent --prod &&     npm prune --prod
 ---> Running in 5dda490d1102
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
npm@6.4.1 /usr/local/lib/node_modules/npm
/usr/local/lib/node_modules/npm/bin/npm-cli.js:85
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
ERROR: Service 'microservice' failed to build: The command '/bin/sh -c npm install --silent -g npm &&     npm install --silent --prod &&     npm prune --prod' returned a non-zero code: 1

**Comment by atammi** [comment]
Update: 
Changed FROM node:4-slim to FROM node:latest in the microservice/Dockerfile and docker-compose up -d finished. But unfortunately in addition to the make-ssh-keys also the following died with Exit 1 : datapower, microservice, nginx.
And after that _docker-compose ps_ hangs indefinitely.

**Comment by atammi** [comment]
Tried FROM node:8 since someone got it working with that. Still complaining that permission denied to write a java security policy file and also about missing public key in a call. nginx, datapower and microservice won't start.
I'm giving up. I believe there are rather many issues with strongloop/apiconnect-docker. It's a shame since I really wanted to learn about it.
