### ISSUE TITLE
docker-compose up -d command fails at Step5 .. See details below

### ISSUE THREAD

**Issue by agitonga** [strongloop/apiconnect-docker#50]
Creating network "apiconnect-docker-master_default" with the default driver
Creating network "apiconnect-docker-master_ibmnet" with the default driver
Building microservice
Step 1/12 : FROM node:4-slim
 ---> c953ec480e11
Step 2/12 : RUN mkdir -p /usr/src/app &&     apt update &&     apt install -y jq &&     rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 78e4a284f471
Step 3/12 : WORKDIR /usr/src/app
 ---> Using cache
 ---> f1594f10f295
Step 4/12 : COPY package.json /usr/src/app/
 ---> Using cache
 ---> 6c3a719365ff
Step 5/12 : RUN npm install --silent -g npm &&     npm install --silent --prod &&     npm prune --prod
 ---> Running in 44d726dbff1f
/usr/local/bin/npm -> /usr/local/lib/node_modules/npm/bin/npm-cli.js
/usr/local/bin/npx -> /usr/local/lib/node_modules/npm/bin/npx-cli.js
npm@6.4.1 /usr/local/lib/node_modules/npm
/usr/local/lib/node_modules/npm/bin/npm-cli.js:85
      let notifier = require('update-notifier')({pkg})
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3
ERROR: Service 'microservice' failed to build: The command '/bin/sh -c npm install --silent -g npm &&     npm install --silent --prod &&     npm prune --prod' returned a non-zero code: 1

**Comment by lukasz-antoniak** [comment]
Update Node version in _microservice/Dockerfile_ to `FROM node:6.14.4-slim`.
